trainer:
  accelerator: auto
  default_root_dir: runs/gwak_simCLR_EffNet_T0.5/
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val/loss
        mode: min
        save_last: true
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val/loss
        patience: 5
        mode: min
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
  log_every_n_steps: 1
  max_epochs: 50

data:
  class_path: data.datasets.GwakDataloader
  init_args:
    batch_size: 350
    num_workers: 1

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1e-3

lr_scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingLR
  init_args:
    T_max: 100
    eta_min: 1e-4

model:
  class_path: models.litmodels.SimCLRModel
  init_args:
    encoder:
      class_path: models.resnet_1d.ResNet1D
      init_args:
        in_channels: 2
        layers: [3,4,6,3]
        classes: 4 
    projector:
      class_path: models.networks.MLP
      init_args:
        input_dim: 4
        hidden_dims: [4]
        output_dim: 4
    classifier:
      class_path: models.networks.MLP
      init_args:
        input_dim: 4
        hidden_dims: [16,16]
        output_dim: 10
    lambda_classifier: 1.0
    temperature: 0.5
    sup_simclr: true
