trainer:
  accelerator: auto
  default_root_dir: runs/imagenette_fineTuneSupSimCLR/
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val/loss
        mode: min
        save_last: true
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val/loss
        patience: 5
        mode: min
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
  log_every_n_steps: 1
  max_epochs: 50

model:
  class_path: models.litmodels.SimCLRModel
  init_args:
    encoder:
      class_path: models.networks.CustomPretrainedResNet
      init_args:
        variant: "resnet50x1"
        fc_hidden: [512,256,128]
        fc_out: 4 # dimension of contrastive space
    projector:
      class_path: models.networks.MLP
      init_args:
        input_dim: 4
        hidden_dims: [4]
        output_dim: 4
        activation: "tanh"
    temperature: 0.5
    sup_simclr: true

data:
  class_path: data.datasets.ImagenetteDataset
  init_args:
    image_width: 224
    sup_simclr: true
    batch_size: 1024
    num_workers: 4
    pin_memory: false

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1e-3

lr_scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingLR
  init_args:
    T_max: 20
    eta_min: 1e-5